import React, { useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';

const green = '#2D6A4F';
const cream = '#F8F7F2';
const meals = [
  ['Mon', '🌯', 'Burritos'], ['Tue', '🍕', 'Pizza Night'], ['Wed', '🍝', 'Sausage Pasta Bake'], ['Thu', '🍔', 'Chicken Burgers'], ['Fri', '🌶️', 'Chilli Con Carne']
];

export default function App() {
  const [tab, setTab] = useState('Home');
  const [cooked, setCooked] = useState([]);
  const [items, setItems] = useState(['Chicken breast fillets', 'Extra large wraps', 'Mexican rice', 'Sausages', 'Diet Coke — 24 cans', 'Kitchen roll', 'Toothpaste']);
  const [checked, setChecked] = useState([]);
  const [newItem, setNewItem] = useState('');
  const tickMeal = name => setCooked(cooked.includes(name) ? cooked.filter(x => x !== name) : [...cooked, name]);
  const tickItem = name => setChecked(checked.includes(name) ? checked.filter(x => x !== name) : [...checked, name]);
  const add = () => { if (newItem.trim()) { setItems([...items, newItem.trim()]); setNewItem(''); } };
  const upcoming = meals.find(m => !cooked.includes(m[2])) || meals[0];
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
    {tab === 'Home' && <>
      <Text style={s.kicker}>GOOD EVENING, JACK</Text><Text style={s.title}>Your weekly shop,{`\n`}sorted.</Text>
      <View style={s.hero}><Text style={s.heroTiny}>TONIGHT</Text><Text style={s.heroTitle}>{upcoming[1]}  {upcoming[2]}</Text><Text style={s.heroText}>Feeds 2 · Chicken expires tomorrow</Text><TouchableOpacity style={s.cookedBtn} onPress={() => tickMeal(upcoming[2])}><Text style={s.cookedText}>✓  Cooked</Text></TouchableOpacity></View>
      <Text style={s.section}>Use first</Text><View style={s.expiryRow}><Expiry emoji="🍗" name="Chicken" time="Tomorrow" red/><Expiry emoji="🥛" name="Milk" time="2 days"/><Expiry emoji="🥣" name="Sour cream" time="3 days"/></View>
      <Text style={s.section}>Your week</Text><View style={s.card}>{meals.slice(0,3).map(m => <Row key={m[2]} label={m[0]} emoji={m[1]} title={m[2]} sub={cooked.includes(m[2]) ? 'Cooked ✓' : 'Feeds 2'} />)}</View>
      <Text style={s.section}>Next shop</Text><View style={s.next}><Text style={s.nextIcon}>🛒</Text><View style={{flex:1}}><Text style={s.bold}>Ready when you are</Text><Text style={s.sub}>7 regular items are likely due</Text></View><TouchableOpacity style={s.review} onPress={() => setTab('Shop')}><Text style={s.reviewText}>Review</Text></TouchableOpacity></View>
    </>}
    {tab === 'Week' && <><Text style={s.kicker}>PLAN MY WEEK</Text><Text style={s.title}>Meals made easy.</Text><Text style={s.lead}>Tap a meal when you have cooked it. We will use that to make the next shop smarter.</Text><View style={s.card}>{meals.map(m => <TouchableOpacity key={m[2]} style={s.meal} onPress={() => tickMeal(m[2])}><Text style={[s.box, cooked.includes(m[2]) && s.boxOn]}>{cooked.includes(m[2]) ? '✓' : ''}</Text><Text style={s.day}>{m[0]}</Text><Text style={s.emoji}>{m[1]}</Text><View style={{flex:1}}><Text style={[s.bold,cooked.includes(m[2]) && s.strike]}>{m[2]}</Text><Text style={s.sub}>{cooked.includes(m[2]) ? 'Cooked' : '2 portions · Tap when cooked'}</Text></View></TouchableOpacity>)}</View></>}
    {tab === 'Shop' && <><Text style={s.kicker}>THIS WEEK'S SHOP</Text><Text style={s.title}>A simpler shop.</Text><View style={s.summary}><Text style={s.summaryBig}>{items.length - checked.length} items</Text><Text style={s.summaryText}>Everything you need, in one place</Text></View><View style={s.add}><TextInput value={newItem} onChangeText={setNewItem} onSubmitEditing={add} placeholder="Add anything… batteries, toothpaste" style={s.input}/><TouchableOpacity onPress={add}><Text style={s.addText}>Add</Text></TouchableOpacity></View><Text style={s.group}>MEALS, REGULARS & EXTRAS</Text><View style={s.card}>{items.map(item => <TouchableOpacity key={item} style={s.meal} onPress={() => tickItem(item)}><Text style={[s.box,checked.includes(item) && s.boxOn]}>{checked.includes(item) ? '✓' : ''}</Text><View style={{flex:1}}><Text style={[s.bold, checked.includes(item) && s.strike]}>{item}</Text><Text style={s.sub}>{item.includes('Diet') || item === 'Kitchen roll' || item === 'Toothpaste' ? 'Probably due this week' : 'Needed for this week’s meals'}</Text></View></TouchableOpacity>)}</View></>}
    {tab === 'Home' ? null : <Text style={s.tip}>This is the first working preview. It will learn your real meals, household regulars and use-by dates once we connect the database.</Text>}
  </ScrollView><View style={s.nav}>{[['Home','⌂'],['Week','▣'],['Shop','🛒'],['Home','⌂'],['More','•••']].map((x,i)=><TouchableOpacity key={i} onPress={() => setTab(x[0])} style={s.navItem}><Text style={s.navIcon}>{x[1]}</Text><Text style={[s.navText,tab===x[0]&&{color:green}]}>{['Home','My Week','Shop','At Home','More'][i]}</Text></TouchableOpacity>)}</View></SafeAreaView>;
}
function Expiry({emoji,name,time,red}) { return <View style={s.expiry}><Text style={{fontSize:26}}>{emoji}</Text><Text style={s.expiryName}>{name}</Text><Text style={[s.expiryTime, red && {color:'#C94D47'}]}>{time}</Text></View> }
function Row({label,emoji,title,sub}) { return <View style={s.row}><Text style={s.day}>{label}</Text><Text style={s.emoji}>{emoji}</Text><View><Text style={s.bold}>{title}</Text><Text style={s.sub}>{sub}</Text></View></View> }
const s = StyleSheet.create({safe:{flex:1,backgroundColor:cream},page:{padding:20,paddingBottom:100},kicker:{color:green,fontSize:11,fontWeight:'800',letterSpacing:1.3,marginTop:12},title:{fontSize:31,fontWeight:'800',lineHeight:37,color:'#202923',marginTop:5,marginBottom:18},hero:{backgroundColor:green,borderRadius:24,padding:21,marginBottom:25},heroTiny:{color:'#D6EFDE',fontSize:11,fontWeight:'800',letterSpacing:1.3},heroTitle:{color:'white',fontSize:21,fontWeight:'800',marginTop:9},heroText:{color:'#D6EFDE',fontSize:13,marginTop:4},cookedBtn:{backgroundColor:'white',alignSelf:'flex-start',borderRadius:14,paddingVertical:10,paddingHorizontal:15,marginTop:17},cookedText:{color:green,fontWeight:'800'},section:{fontSize:19,fontWeight:'800',color:'#202923',marginBottom:10,marginTop:3},expiryRow:{flexDirection:'row',gap:9,marginBottom:24},expiry:{flex:1,backgroundColor:'white',borderRadius:16,padding:12,alignItems:'center'},expiryName:{fontSize:11,fontWeight:'800',marginTop:6},expiryTime:{fontSize:11,color:'#D8922B',fontWeight:'800',marginTop:3},card:{backgroundColor:'white',borderRadius:20,overflow:'hidden',marginBottom:24},row:{padding:15,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#E8E9E2'},day:{width:35,color:'#66736A',fontSize:12,fontWeight:'800'},emoji:{fontSize:22,marginRight:11},bold:{fontSize:15,fontWeight:'800',color:'#202923'},sub:{fontSize:12,color:'#66736A',marginTop:3},next:{backgroundColor:'#EFE8DA',borderRadius:20,padding:15,flexDirection:'row',alignItems:'center',gap:11},nextIcon:{fontSize:26},review:{backgroundColor:green,borderRadius:13,paddingVertical:10,paddingHorizontal:14},reviewText:{color:'white',fontWeight:'800'},lead:{fontSize:15,lineHeight:22,color:'#66736A',marginBottom:20},meal:{padding:15,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#E8E9E2'},box:{width:22,height:22,borderWidth:1.5,borderColor:'#CAD4CC',borderRadius:7,marginRight:11,textAlign:'center',color:'white',fontWeight:'800'},boxOn:{backgroundColor:green,borderColor:green},strike:{textDecorationLine:'line-through',color:'#66736A'},summary:{backgroundColor:'#DCEDE2',borderRadius:18,padding:17,marginBottom:13},summaryBig:{fontSize:21,fontWeight:'800',color:green},summaryText:{fontSize:13,color:green,marginTop:4},add:{backgroundColor:'white',borderRadius:15,paddingLeft:15,flexDirection:'row',alignItems:'center',marginBottom:22},input:{flex:1,height:50,fontSize:14},addText:{color:green,fontWeight:'800',padding:16},group:{fontSize:11,fontWeight:'800',letterSpacing:1.1,color:'#66736A',marginBottom:8},tip:{fontSize:13,lineHeight:19,color:'#66736A',textAlign:'center',marginTop:8},nav:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:'white',borderTopWidth:1,borderColor:'#E8E9E2',flexDirection:'row',paddingVertical:9},navItem:{flex:1,alignItems:'center'},navIcon:{fontSize:18},navText:{fontSize:9,color:'#66736A',marginTop:3,fontWeight:'700'}});
