import React, { useMemo, useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

const C={ink:'#18201D',muted:'#66706B',green:'#315F4A',dark:'#244838',soft:'#E7EFEA',bg:'#F4F5F2',white:'#FFF',line:'#DDE2DE',amber:'#9A6A25',amberSoft:'#F7EEDF',red:'#A74642'};
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const MEALS={
  'Chicken burritos':{time:30,ingredients:[['Chicken breast',1,'pack','2026-09-09',true],['Wraps',1,'pack',null,false],['Rice',1,'pouch',null,false],['Cheddar',1,'pack','2026-09-18',true],['Tomatoes',2,'items','2026-09-12',true]]},
  'Mexican rice pan':{time:25,ingredients:[['Beef mince',1,'pack','2026-09-10',true],['Mexican rice',1,'pouch',null,false],['Peppers',2,'items','2026-09-13',true],['Chorizo',1,'pack','2026-09-20',true]]},
  'Pizza night':{time:20,ingredients:[['Frozen pizza',2,'items',null,false],['Garlic bread',1,'pack',null,false]]},
  'Sausage pasta bake':{time:40,ingredients:[['Sausages',1,'pack','2026-09-11',true],['Pasta',1,'pack',null,false],['Pasta sauce',1,'jar',null,false],['Mozzarella',1,'pack','2026-09-15',true]]},
  'Chilli con carne':{time:35,ingredients:[['Beef mince',1,'pack','2026-09-10',true],['Kidney beans',1,'tin',null,false],['Chopped tomatoes',1,'tin',null,false],['Rice',1,'pack',null,false]]},
  'Chicken burgers':{time:25,ingredients:[['Chicken burgers',2,'items','2026-09-10',true],['Burger buns',1,'pack','2026-09-12',true],['Oven chips',1,'bag',null,false]]},
  'Jacket potatoes':{time:60,ingredients:[['Baking potatoes',2,'items','2026-09-16',true],['Tuna',1,'tin',null,false],['Cheddar',1,'pack','2026-09-18',true]]},
};
const initialCurrent={'Monday':'Chicken burritos','Tuesday':'Mexican rice pan','Wednesday':'Pizza night','Thursday':'Sausage pasta bake','Friday':'Chilli con carne','Saturday':'Chicken burgers','Sunday':'Jacket potatoes'};
const initialNext={'Monday':'Sausage pasta bake','Tuesday':'Chicken burritos','Wednesday':'Pizza night','Thursday':'Mexican rice pan','Friday':'Chilli con carne','Saturday':'Chicken burgers','Sunday':'Jacket potatoes'};
const money=n=>`£${(n/100).toFixed(2)}`;
const shops=[['Tesco',5148],['Morrisons',5295],["Sainsbury's",5372]];

export default function App(){
 const[started,setStarted]=useState(false),[tab,setTab]=useState('This Week'),[page,setPage]=useState('');
 const[shopDay,setShopDay]=useState('Friday'),[current,setCurrent]=useState(initialCurrent),[next,setNext]=useState(initialNext);
 const[outcomes,setOutcomes]=useState({}),[basketExtras,setBasketExtras]=useState(['Toilet roll','Toothpaste']),[extra,setExtra]=useState('');
 const[checkoutShop,setCheckoutShop]=useState(''),[delivery,setDelivery]=useState(''),[arrivalLogged,setArrivalLogged]=useState(false);
 const[dates,setDates]=useState({'Chicken breast':'2026-09-09','Beef mince':'2026-09-10','Sausages':'2026-09-11'}),[pantry,setPantry]=useState({'Chicken breast':1,'Wraps':1,'Rice':2,'Cheddar':1,'Tomatoes':4,'Milk':1});
 const basket=useMemo(()=>buildBasket(next,basketExtras),[next,basketExtras]);
 const suggestion=useMemo(()=>findExpirySuggestion(current,dates),[current,dates]);
 const chooseMeal=(day,meal)=>{setNext(p=>({...p,[day]:meal}));setPage('');setTab('Plan Shop')};
 const finishDay=(day,type)=>{setOutcomes(p=>({...p,[day]:type}));if(type==='Cooked'){const meal=MEALS[current[day]];setPantry(p=>{let n={...p};meal.ingredients.forEach(([name,qty])=>n[name]=Math.max(0,(n[name]||0)-qty));return n})}};
 if(!started)return <SafeAreaView style={s.welcome}><View style={s.logo}><Text style={s.logoText}>OWS</Text></View><Text style={s.welcomeTitle}>Our Weekly Shop</Text><Text style={s.welcomeSub}>Plan once. Stay organised all week.</Text><Text style={s.copy}>Choose when you normally shop. We will keep this week’s meals separate from the shop you are planning for next week.</Text><Text style={s.label}>MY WEEKLY SHOP DAY</Text><View style={s.dayPicker}>{['Thursday','Friday','Saturday','Sunday'].map(d=><TouchableOpacity key={d} style={[s.dayPill,shopDay===d&&s.dayPillOn]} onPress={()=>setShopDay(d)}><Text style={[s.dayPillText,shopDay===d&&s.dayPillTextOn]}>{d.slice(0,3)}</Text></TouchableOpacity>)}</View><TouchableOpacity style={s.button} onPress={()=>setStarted(true)}><Text style={s.buttonText}>Continue to my week</Text></TouchableOpacity><Text style={s.demo}>INTERACTIVE WORKFLOW PREVIEW</Text></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  {page?<Sub page={page} back={()=>setPage('')} next={next} chooseMeal={chooseMeal} shopDay={shopDay} setShopDay={setShopDay} basket={basket} checkoutShop={checkoutShop} setCheckoutShop={setCheckoutShop} delivery={delivery} setDelivery={setDelivery} setArrivalLogged={setArrivalLogged} dates={dates} setDates={setDates}/>:<>
   {tab==='This Week'&&<ThisWeek plan={current} outcomes={outcomes} finishDay={finishDay} suggestion={suggestion} setCurrent={setCurrent}/>} 
   {tab==='Plan Shop'&&<PlanShop plan={next} shopDay={shopDay} open={setPage} basket={basket}/>} 
   {tab==='Basket'&&<Basket basket={basket} extras={basketExtras} setExtras={setBasketExtras} extra={extra} setExtra={setExtra} open={setPage} checkoutShop={checkoutShop} delivery={delivery}/>} 
   {tab==='At Home'&&<AtHome pantry={pantry} arrivalLogged={arrivalLogged} delivery={delivery} dates={dates} open={setPage}/>} 
   {tab==='Account'&&<Account shopDay={shopDay} open={setPage} reset={()=>setStarted(false)}/>} 
  </>}
 </ScrollView>{!page&&<Nav tab={tab} setTab={setTab}/>}</SafeAreaView>
}

function buildBasket(plan,extras){const map={};Object.values(plan).forEach(mealName=>{const meal=MEALS[mealName];if(meal)meal.ingredients.forEach(([name,qty,unit,,dated])=>{if(!map[name])map[name]={name,qty:0,unit,dated,meals:[]};map[name].qty+=qty;if(!map[name].meals.includes(mealName))map[name].meals.push(mealName)})});extras.forEach(name=>map[name]={name,qty:1,unit:'item',dated:false,meals:['Household']});return Object.values(map)}
function findExpirySuggestion(plan,dates){
 for(const day of DAYS){
  const meal=MEALS[plan[day]];
  if(!meal)continue;
  for(const [name] of meal.ingredients){
   const plannedDate=new Date(`2026-09-${8+DAYS.indexOf(day)}T12:00:00`);
   const useBy=dates[name]?new Date(`${dates[name]}T12:00:00`):null;
   if(useBy&&useBy<plannedDate){
    return {name,meal:plan[day],from:day,to:DAYS[Math.max(0,useBy.getDate()-8)]||'Monday',date:dates[name]};
   }
  }
 }
 return null;
}

function ThisWeek({plan,outcomes,finishDay,suggestion,setCurrent}){const[today]=useState('Monday');return <><Header overline="MEAL PLAN · THIS WEEK" title="Your week" sub="Everything already planned for the next seven days."/>{suggestion&&<View style={s.alert}><View style={s.alertIcon}><Ionicons name="time-outline" size={20} color={C.amber}/></View><View style={{flex:1}}><Text style={s.alertTitle}>Use-by date suggestion</Text><Text style={s.alertText}>{suggestion.name} is dated {niceDate(suggestion.date)}. Move {suggestion.meal} from {suggestion.from} to {suggestion.to}?</Text><TouchableOpacity onPress={()=>{const a=plan[suggestion.from],b=plan[suggestion.to];setCurrent(p=>({...p,[suggestion.from]:b,[suggestion.to]:a}))}}><Text style={s.link}>Move meal automatically</Text></TouchableOpacity></View></View>}
 <View style={s.weekCard}>{DAYS.map((day,i)=>{const status=outcomes[day];return <View key={day} style={[s.calendarRow,day===today&&s.todayRow]}><View style={s.date}><Text style={[s.dayShort,day===today&&{color:C.green}]}>SEP</Text><Text style={s.dateNo}>{8+i}</Text></View><View style={{flex:1}}><View style={s.dayHeading}><Text style={s.dayName}>{day}</Text>{day===today&&<Text style={s.today}>TODAY</Text>}</View><Text style={[s.mealName,status&&s.crossed]}>{plan[day]}</Text><Text style={s.mealMeta}>{MEALS[plan[day]].time} minutes · Dinner</Text>{day===today&&!status&&<View style={s.outcomeRow}><SmallButton icon="checkmark" text="Cooked" onPress={()=>finishDay(day,'Cooked')}/><SmallButton icon="restaurant-outline" text="Ate out" onPress={()=>finishDay(day,'Ate out')} pale/><SmallButton icon="bag-handle-outline" text="Takeaway" onPress={()=>finishDay(day,'Takeaway')} pale/></View>}{status&&<View style={s.status}><Ionicons name={status==='Cooked'?'checkmark-circle':'information-circle'} size={15} color={C.green}/><Text style={s.statusText}>{status}{status==='Cooked'?' · ingredients removed from home stock':' · no ingredients used'}</Text></View>}</View></View>})}</View>
 <View style={s.info}><Ionicons name="notifications-outline" size={19} color={C.green}/><Text style={s.infoText}>Each evening, the app will remind you to confirm whether the planned meal was cooked, skipped or replaced.</Text></View></>}

function PlanShop({plan,shopDay,open,basket}){return <><Header overline="UPCOMING WEEK" title="Plan your shop" sub={`Your next shop is ${shopDay}. Choose dinner for each day of the following week.`}/><View style={s.progress}><View style={s.progressTop}><Text style={s.progressTitle}>Next week</Text><Text style={s.progressCount}>7 of 7 dinners planned</Text></View><View style={s.track}><View style={[s.trackFill,{width:'100%'}]}/></View></View><View style={s.weekCard}>{DAYS.map((day,i)=><TouchableOpacity key={day} style={s.planRow} onPress={()=>open(`Choose:${day}`)}><View style={s.date}><Text style={s.dayShort}>SEP</Text><Text style={s.dateNo}>{15+i}</Text></View><View style={{flex:1}}><Text style={s.dayName}>{day}</Text><Text style={s.mealName}>{plan[day]}</Text><Text style={s.mealMeta}>{MEALS[plan[day]].time} minutes · ingredients added</Text></View><Ionicons name="chevron-forward" size={18} color={C.muted}/></TouchableOpacity>)}</View><View style={s.basketCallout}><View style={s.iconBox}><Ionicons name="basket-outline" size={21} color={C.green}/></View><View style={{flex:1}}><Text style={s.rowTitle}>Shopping list created</Text><Text style={s.rowDetail}>{basket.length} products calculated from next week’s meals</Text></View></View></>}

function Basket({basket,extras,setExtras,extra,setExtra,open,checkoutShop,delivery}){const add=()=>{if(extra.trim()){setExtras(p=>[...p,extra.trim()]);setExtra('')}};return <><Header overline="NEXT SHOP" title="Your basket" sub="Meal ingredients and anything else your household needs."/><View style={s.addBar}><Ionicons name="add" size={20} color={C.green}/><TextInput value={extra} onChangeText={setExtra} onSubmitEditing={add} placeholder="Add toilet roll, toothpaste, batteries…" placeholderTextColor={C.muted} style={s.input}/><TouchableOpacity onPress={add}><Text style={s.link}>Add</Text></TouchableOpacity></View><Text style={s.sectionLabel}>MEAL INGREDIENTS</Text><View style={s.card}>{basket.filter(x=>x.meals[0]!=='Household').map(item=><Item key={item.name} item={item}/>)}</View><Text style={s.sectionLabel}>OTHER ITEMS</Text><View style={s.card}>{basket.filter(x=>x.meals[0]==='Household').map(item=><View key={item.name} style={s.itemRow}><View style={s.tick}><Ionicons name="checkmark" size={14} color={C.green}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{item.name}</Text><Text style={s.rowDetail}>Added manually</Text></View><TouchableOpacity onPress={()=>setExtras(p=>p.filter(x=>x!==item.name))}><Ionicons name="trash-outline" size={18} color={C.muted}/></TouchableOpacity></View>)}</View>{checkoutShop?<View style={s.confirm}><Ionicons name="checkmark-circle" size={22} color={C.green}/><View style={{flex:1}}><Text style={s.confirmTitle}>Basket sent to {checkoutShop}</Text><Text style={s.rowDetail}>{delivery?`Expected ${delivery}`:'Add the delivery or collection time when checkout is complete.'}</Text></View></View>:null}<Button text={checkoutShop?'Update delivery details':'Compare and choose supermarket'} icon="stats-chart-outline" onPress={()=>open('Compare')}/></>}
function Item({item}){return <View style={s.itemRow}><View style={s.tick}><Ionicons name="checkmark" size={14} color={C.green}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{item.name}</Text><Text style={s.rowDetail}>{item.qty} {item.unit}{item.qty>1?'s':''} · {item.meals.slice(0,2).join(', ')}</Text></View>{item.dated&&<Text style={s.fresh}>FRESH</Text>}</View>}

function AtHome({pantry,arrivalLogged,delivery,dates,open}){return <><Header overline="HOUSEHOLD STOCK" title="What’s at home" sub="Updated automatically as shopping arrives and meals are completed."/>{delivery&&!arrivalLogged&&<View style={s.arrival}><Ionicons name="cube-outline" size={22} color={C.green}/><View style={{flex:1}}><Text style={s.rowTitle}>Your shop is due {delivery}</Text><Text style={s.rowDetail}>When it arrives, log the dates on short-life products.</Text></View><TouchableOpacity onPress={()=>open('Dates')}><Text style={s.link}>Log dates</Text></TouchableOpacity></View>}<Text style={s.sectionLabel}>SHORT-LIFE PRODUCTS</Text><View style={s.card}>{Object.entries(dates).map(([name,date])=><View key={name} style={s.itemRow}><View style={s.iconBox}><Ionicons name="calendar-outline" size={18} color={C.green}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{name}</Text><Text style={s.rowDetail}>Use by {niceDate(date)}</Text></View></View>)}</View><Text style={s.sectionLabel}>CUPBOARD AND FRIDGE</Text><View style={s.card}>{Object.entries(pantry).filter(([,q])=>q>0).map(([name,q])=><View key={name} style={s.itemRow}><View style={s.iconBox}><Ionicons name="cube-outline" size={18} color={C.green}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{name}</Text><Text style={s.rowDetail}>{q} remaining</Text></View></View>)}</View></>}

function Account({shopDay,open,reset}){return <><Header overline="ACCOUNT" title="Your household" sub="Preferences that power your weekly routine."/><View style={s.card}><Setting icon="people-outline" name="Household members" detail="Jack and Gemma"/><Setting icon="calendar-outline" name="Weekly shop day" detail={shopDay} onPress={()=>open('ShopDay')}/><Setting icon="storefront-outline" name="Supermarket accounts" detail="Connect when partners approve access"/><Setting icon="notifications-outline" name="Reminders" detail="Meal and delivery prompts enabled"/><Setting icon="shield-checkmark-outline" name="Privacy and permissions" detail="You control every connection"/></View><Button text="Preview setup again" pale onPress={reset}/></>}
function Setting({icon,name,detail,onPress}){return <TouchableOpacity disabled={!onPress} onPress={onPress} style={s.itemRow}><View style={s.iconBox}><Ionicons name={icon} size={19} color={C.green}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{name}</Text><Text style={s.rowDetail}>{detail}</Text></View>{onPress&&<Ionicons name="chevron-forward" size={18} color={C.muted}/>}</TouchableOpacity>}

function Sub({page,back,next,chooseMeal,shopDay,setShopDay,basket,checkoutShop,setCheckoutShop,delivery,setDelivery,setArrivalLogged,dates,setDates}){
 if(page.startsWith('Choose:')){
  const day=page.split(':')[1];
  return <><Back onPress={back}/><Header overline="CHOOSE DINNER" title={day} sub="Selecting a meal updates your shopping list immediately."/><View style={s.card}>{Object.entries(MEALS).map(([name,meal])=><TouchableOpacity key={name} style={[s.mealChoice,next[day]===name&&s.mealChoiceOn]} onPress={()=>chooseMeal(day,name)}><View style={s.iconBox}><Ionicons name="restaurant-outline" size={19} color={C.green}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{name}</Text><Text style={s.rowDetail}>{meal.time} minutes · {meal.ingredients.length} ingredients</Text></View>{next[day]===name&&<Ionicons name="checkmark-circle" size={21} color={C.green}/>}</TouchableOpacity>)}</View></>;
 }
 if(page==='Compare')return <Compare back={back} basket={basket} checkoutShop={checkoutShop} setCheckoutShop={setCheckoutShop} delivery={delivery} setDelivery={setDelivery}/>;
 if(page==='Dates')return <Dates back={back} dates={dates} setDates={setDates} done={()=>{setArrivalLogged(true);back()}}/>;
 if(page==='ShopDay')return <><Back onPress={back}/><Header overline="SHOP ROUTINE" title="Weekly shop day" sub="We will prompt you to plan the upcoming week before this day."/><View style={s.card}>{DAYS.map(day=><TouchableOpacity key={day} style={s.itemRow} onPress={()=>{setShopDay(day);back()}}><Text style={[s.rowTitle,{flex:1}]}>{day}</Text>{shopDay===day&&<Ionicons name="checkmark-circle" size={21} color={C.green}/>}</TouchableOpacity>)}</View></>;
 return null;
}
function Compare({back,basket,checkoutShop,setCheckoutShop,delivery,setDelivery}){const[chosen,setChosen]=useState(checkoutShop),[timing,setTiming]=useState(delivery);return <><Back onPress={back}/><Header overline="FULL BASKET COMPARISON" title="Choose a supermarket" sub={`${basket.length} products compared. Demo prices shown.`}/>{shops.map(([name,total],i)=><TouchableOpacity key={name} style={[s.shop,i===0&&s.best,chosen===name&&s.selected]} onPress={()=>setChosen(name)}><View style={s.shopTop}><View><Text style={s.shopName}>{name}</Text><Text style={s.rowDetail}>{basket.length}/{basket.length} products matched</Text></View>{i===0&&<Text style={s.bestTag}>BEST VALUE</Text>}</View><Text style={s.shopTotal}>{money(total)}</Text><Text style={s.shopSaving}>Estimated basket total</Text>{chosen===name&&<View style={s.permission}><Ionicons name="shield-checkmark-outline" size={18} color={C.green}/><Text style={s.permissionText}>You will be asked for permission before connecting. Checkout remains on {name}.</Text></View>}</TouchableOpacity>)}{chosen&&<><Text style={s.sectionLabel}>AFTER CHECKOUT, WHEN IS IT ARRIVING?</Text><View style={s.optionRow}>{['Sat 10:00','Sat 15:00','Sun 10:00'].map(t=><TouchableOpacity key={t} style={[s.option,timing===t&&s.optionOn]} onPress={()=>setTiming(t)}><Text style={[s.optionText,timing===t&&{color:C.white}]}>{t}</Text></TouchableOpacity>)}</View><Button text={`Save ${chosen} shop`} onPress={()=>{setCheckoutShop(chosen);setDelivery(timing);back()}} disabled={!timing}/></>}</>}
function Dates({back,dates,setDates,done}){return <><Back onPress={back}/><Header overline="PUTTING YOUR SHOP AWAY" title="Log use-by dates" sub="Only short-life products are shown. This takes under a minute and allows the app to protect food from waste."/><View style={s.card}>{Object.entries(dates).map(([name,date])=><View key={name} style={s.dateInputRow}><View style={{flex:1}}><Text style={s.rowTitle}>{name}</Text><Text style={s.rowDetail}>Use by date</Text></View><TextInput value={date} onChangeText={value=>setDates(p=>({...p,[name]:value}))} style={s.dateInput}/></View>)}</View><View style={s.info}><Ionicons name="sparkles-outline" size={19} color={C.green}/><Text style={s.infoText}>Once saved, meal order is checked automatically and earlier meal suggestions appear when needed.</Text></View><Button text="Save dates and assess meal plan" onPress={done}/></>}

function Header({overline,title,sub}){return <View style={s.header}><Text style={s.overline}>{overline}</Text><Text style={s.title}>{title}</Text><Text style={s.subtitle}>{sub}</Text></View>}
function Back({onPress}){return <TouchableOpacity style={s.back} onPress={onPress}><Ionicons name="arrow-back" size={19} color={C.green}/><Text style={s.link}>Back</Text></TouchableOpacity>}
function Button({text,onPress,icon,pale,disabled}){return <TouchableOpacity disabled={disabled} onPress={onPress} style={[s.button,pale&&s.buttonPale,disabled&&{opacity:.4}]}>{icon&&<Ionicons name={icon} size={18} color={pale?C.green:C.white}/>}<Text style={[s.buttonText,pale&&{color:C.green}]}>{text}</Text></TouchableOpacity>}
function SmallButton({icon,text,onPress,pale}){return <TouchableOpacity onPress={onPress} style={[s.smallButton,pale&&s.smallPale]}><Ionicons name={icon} size={15} color={pale?C.green:C.white}/><Text style={[s.smallText,pale&&{color:C.green}]}>{text}</Text></TouchableOpacity>}
function Nav({tab,setTab}){const tabs=[['This Week','calendar-outline','calendar'],['Plan Shop','create-outline','create'],['Basket','basket-outline','basket'],['At Home','cube-outline','cube'],['Account','person-outline','person']];return <View style={s.nav}>{tabs.map(([name,off,on])=><TouchableOpacity key={name} style={s.navItem} onPress={()=>setTab(name)}><Ionicons name={tab===name?on:off} size={20} color={tab===name?C.green:C.muted}/><Text style={[s.navText,tab===name&&s.navTextOn]}>{name}</Text></TouchableOpacity>)}</View>}
function niceDate(date){if(!date)return'No date';return new Date(`${date}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}

const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:C.bg},content:{padding:20,paddingBottom:105},welcome:{flex:1,backgroundColor:C.bg,justifyContent:'center',alignItems:'center',padding:30},logo:{width:66,height:66,borderRadius:17,backgroundColor:C.green,justifyContent:'center',alignItems:'center'},logoText:{color:C.white,fontSize:19,fontWeight:'800',letterSpacing:1},welcomeTitle:{fontSize:31,fontWeight:'700',color:C.ink,marginTop:22},welcomeSub:{fontSize:16,fontWeight:'600',color:C.green,marginTop:6},copy:{fontSize:14,lineHeight:22,color:C.muted,textAlign:'center',marginVertical:23,maxWidth:380},label:{fontSize:9,fontWeight:'800',letterSpacing:1.3,color:C.muted,alignSelf:'stretch',marginBottom:9},dayPicker:{flexDirection:'row',gap:7,alignSelf:'stretch'},dayPill:{flex:1,borderWidth:1,borderColor:C.line,borderRadius:9,paddingVertical:10,alignItems:'center',backgroundColor:C.white},dayPillOn:{backgroundColor:C.green,borderColor:C.green},dayPillText:{fontSize:12,fontWeight:'700',color:C.muted},dayPillTextOn:{color:C.white},demo:{fontSize:9,fontWeight:'700',letterSpacing:1.2,color:C.muted,marginTop:28},
 header:{paddingTop:18,paddingBottom:22},overline:{fontSize:10,fontWeight:'800',letterSpacing:1.6,color:C.green,marginBottom:7},title:{fontSize:29,lineHeight:35,fontWeight:'700',letterSpacing:-.5,color:C.ink},subtitle:{fontSize:13,lineHeight:20,color:C.muted,marginTop:7},link:{fontSize:13,fontWeight:'700',color:C.green},back:{paddingTop:14,flexDirection:'row',alignItems:'center',gap:7},
 alert:{backgroundColor:C.amberSoft,borderWidth:1,borderColor:'#E8D5B7',borderRadius:13,padding:14,flexDirection:'row',gap:11,marginBottom:17},alertIcon:{width:36,height:36,borderRadius:10,backgroundColor:C.white,alignItems:'center',justifyContent:'center'},alertTitle:{fontSize:14,fontWeight:'700',color:C.ink},alertText:{fontSize:12,lineHeight:18,color:C.muted,marginTop:4,marginBottom:7},weekCard:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:14,overflow:'hidden',marginBottom:18},calendarRow:{padding:14,flexDirection:'row',gap:13,borderBottomWidth:1,borderBottomColor:C.line},todayRow:{backgroundColor:'#F6FAF7'},date:{width:39,alignItems:'center'},dayShort:{fontSize:8,fontWeight:'800',letterSpacing:1,color:C.muted},dateNo:{fontSize:21,fontWeight:'700',color:C.ink,marginTop:2},dayHeading:{flexDirection:'row',alignItems:'center',gap:7},dayName:{fontSize:11,fontWeight:'700',color:C.muted},today:{fontSize:8,fontWeight:'800',letterSpacing:.8,color:C.green,backgroundColor:C.soft,paddingHorizontal:6,paddingVertical:3,borderRadius:5},mealName:{fontSize:15,fontWeight:'700',color:C.ink,marginTop:4},mealMeta:{fontSize:11,color:C.muted,marginTop:3},crossed:{textDecorationLine:'line-through',color:C.muted},outcomeRow:{flexDirection:'row',gap:6,marginTop:11,flexWrap:'wrap'},smallButton:{borderRadius:7,paddingVertical:7,paddingHorizontal:9,backgroundColor:C.green,flexDirection:'row',alignItems:'center',gap:4},smallPale:{backgroundColor:C.soft},smallText:{fontSize:10,fontWeight:'700',color:C.white},status:{flexDirection:'row',alignItems:'center',gap:5,marginTop:9},statusText:{fontSize:10,fontWeight:'600',color:C.green},
 info:{backgroundColor:C.soft,borderRadius:11,padding:14,flexDirection:'row',gap:9,alignItems:'flex-start',marginBottom:18},infoText:{flex:1,fontSize:12,lineHeight:18,color:C.dark},progress:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:12,padding:15,marginBottom:13},progressTop:{flexDirection:'row',justifyContent:'space-between'},progressTitle:{fontSize:14,fontWeight:'700',color:C.ink},progressCount:{fontSize:11,color:C.muted},track:{height:6,borderRadius:3,backgroundColor:C.soft,marginTop:12},trackFill:{height:6,borderRadius:3,backgroundColor:C.green},planRow:{padding:14,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:C.line},basketCallout:{backgroundColor:C.soft,borderRadius:12,padding:14,flexDirection:'row',alignItems:'center',gap:11},iconBox:{width:36,height:36,borderRadius:9,backgroundColor:C.soft,alignItems:'center',justifyContent:'center'},rowTitle:{fontSize:14,fontWeight:'700',color:C.ink},rowDetail:{fontSize:11,color:C.muted,marginTop:3},
 addBar:{height:50,backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:11,paddingHorizontal:13,flexDirection:'row',alignItems:'center',marginBottom:22},input:{flex:1,fontSize:13,color:C.ink,paddingHorizontal:9},sectionLabel:{fontSize:9,fontWeight:'800',letterSpacing:1.2,color:C.muted,marginBottom:8},card:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:13,overflow:'hidden',marginBottom:22},itemRow:{padding:13,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:C.line},tick:{width:22,height:22,borderRadius:6,backgroundColor:C.soft,alignItems:'center',justifyContent:'center'},fresh:{fontSize:8,fontWeight:'800',letterSpacing:.8,color:C.green,backgroundColor:C.soft,padding:5,borderRadius:5},confirm:{backgroundColor:C.soft,borderRadius:12,padding:14,flexDirection:'row',alignItems:'center',gap:10,marginBottom:12},confirmTitle:{fontSize:14,fontWeight:'700',color:C.green},arrival:{backgroundColor:C.amberSoft,borderWidth:1,borderColor:'#E8D5B7',borderRadius:12,padding:14,flexDirection:'row',alignItems:'center',gap:10,marginBottom:21},
 mealChoice:{padding:14,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:C.line},mealChoiceOn:{backgroundColor:'#F6FAF7'},shop:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:13,padding:16,marginBottom:10},best:{borderWidth:2,borderColor:C.green},selected:{backgroundColor:'#F6FAF7'},shopTop:{flexDirection:'row',justifyContent:'space-between'},shopName:{fontSize:19,fontWeight:'700',color:C.ink},bestTag:{fontSize:8,fontWeight:'800',letterSpacing:1,color:C.green,backgroundColor:C.soft,paddingHorizontal:7,paddingVertical:5,borderRadius:5},shopTotal:{fontSize:27,fontWeight:'700',color:C.green,marginTop:15},shopSaving:{fontSize:11,color:C.muted,marginTop:2},permission:{backgroundColor:C.soft,borderRadius:9,padding:10,flexDirection:'row',gap:7,marginTop:13},permissionText:{flex:1,fontSize:10,lineHeight:15,color:C.dark},optionRow:{flexDirection:'row',gap:8,marginBottom:8},option:{flex:1,borderWidth:1,borderColor:C.line,borderRadius:8,paddingVertical:10,alignItems:'center',backgroundColor:C.white},optionOn:{backgroundColor:C.green,borderColor:C.green},optionText:{fontSize:11,fontWeight:'700',color:C.muted},dateInputRow:{padding:14,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:C.line},dateInput:{width:110,borderWidth:1,borderColor:C.line,borderRadius:8,padding:9,fontSize:12,color:C.ink,backgroundColor:C.bg},
 button:{minHeight:48,borderRadius:10,backgroundColor:C.green,paddingHorizontal:16,marginTop:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},buttonPale:{backgroundColor:C.soft},buttonText:{fontSize:14,fontWeight:'700',color:C.white},nav:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:C.white,borderTopWidth:1,borderTopColor:C.line,flexDirection:'row',paddingTop:10,paddingBottom:12},navItem:{flex:1,alignItems:'center',gap:3},navText:{fontSize:8,fontWeight:'600',color:C.muted},navTextOn:{fontWeight:'700',color:C.green},
});
