import React, { useMemo, useState } from 'react';
import { Image, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';

const C={green:'#2D6A4F',cream:'#F8F7F2',ink:'#202923',muted:'#66736A',line:'#E5E8E3',white:'#FFF',soft:'#DCEDE2'};
const bases=['Chicken Breast','Beef Mince','Sausages','Salmon Fillets','Milk','Cheddar Cheese','Yoghurt','Eggs','White Bread','Wraps','Burger Buns','Pasta','Rice','Chopped Tomatoes','Kidney Beans','Potatoes','Onions','Cucumber','Frozen Pizza','Oven Chips'];
const variants=['Value','Everyday','Classic','Large','Family','Twin Pack','Premium','Organic','Easy Open','Bulk','Light','Finest','Fresh','Free Range','Plant Based','Extra Large','Mini','Resealable','Low Fat','Limited'];
const brands=['Meadow & Mill','Oakfield','Harbour Kitchen','Green Lane','Northbrook','Pantry House','River & Rye','Willow Farm'];
const colours=['DDEBDD','F3E4C7','E7DDEA','D9E8F4','F4DDD9','E7E7D5','DDE7E9','EFE1C9'];
const products=bases.flatMap((name,bi)=>variants.map((variant,vi)=>{const id=bi*20+vi+1;const brand=brands[(bi+vi)%brands.length];const pack=bi<4?`${400+(vi%5)*100}g`:bi===4?`${1+(vi%3)}L`:bi<11?`${4+(vi%5)} pack`:`${250+(vi%6)*250}g`;return{id,name:`${name} ${variant}`,brand,pack,base:80+(id*37)%620,image:`https://placehold.co/220x220/${colours[(bi+vi)%colours.length].slice(1)}/2D6A4F?text=${encodeURIComponent(brand+'\n'+name)}`}}));
const shops=[{id:'tesco',name:'Tesco',factor:1},{id:'sainsburys',name:"Sainsbury's",factor:1.035},{id:'morrisons',name:'Morrisons',factor:1.02}];
const money=p=>`£${(p/100).toFixed(2)}`;

export default function App(){
 const [screen,setScreen]=useState('products'),[query,setQuery]=useState(''),[basket,setBasket]=useState({});
 const visible=useMemo(()=>products.filter(p=>(p.name+' '+p.brand).toLowerCase().includes(query.toLowerCase())).slice(0,30),[query]);
 const lines=Object.entries(basket).map(([id,qty])=>({...products[+id-1],qty}));
 const add=p=>setBasket(b=>({...b,[p.id]:(b[p.id]||0)+1}));
 const remove=p=>setBasket(b=>{const n={...b};if(n[p.id]>1)n[p.id]--;else delete n[p.id];return n});
 const totals=shops.map((s,si)=>{const normal=lines.reduce((sum,p)=>sum+Math.round(p.base*s.factor+(p.id%7)*si*3)*p.qty,0);const loyalty=normal-lines.reduce((sum,p)=>sum+(p.id%3===0?Math.round(p.base*.1)*p.qty:0),0);return{...s,normal,loyalty}}).sort((a,b)=>a.loyalty-b.loyalty);
 return <SafeAreaView style={s.safe}><View style={s.top}><View><Text style={s.kicker}>OUR WEEKLY SHOP</Text><Text style={s.logo}>{screen==='products'?'Pick your products.':screen==='basket'?'Your basket.':'Compare your shop.'}</Text></View><TouchableOpacity style={s.basketBtn} onPress={()=>setScreen('basket')}><Text style={s.basketText}>🛒 {lines.reduce((a,x)=>a+x.qty,0)}</Text></TouchableOpacity></View>
 <ScrollView contentContainerStyle={s.page}>
 {screen==='products'&&<><TextInput style={s.search} value={query} onChangeText={setQuery} placeholder="Search 400 products or brands…"/><Text style={s.note}>400 fictional products for testing · showing first {visible.length}</Text><View style={s.grid}>{visible.map(p=><View key={p.id} style={s.product}><Image source={{uri:p.image}} style={s.image}/><Text style={s.brand}>{p.brand}</Text><Text style={s.productName} numberOfLines={2}>{p.name}</Text><Text style={s.pack}>{p.pack}</Text><View style={s.priceRow}><Text style={s.from}>from {money(Math.round(p.base*.98))}</Text><TouchableOpacity style={s.add} onPress={()=>add(p)}><Text style={s.addText}>{basket[p.id]?`+ (${basket[p.id]})`:'Add'}</Text></TouchableOpacity></View></View>)}</View></>}
 {screen==='basket'&&<>{!lines.length?<View style={s.empty}><Text style={s.emptyIcon}>🛒</Text><Text style={s.emptyTitle}>Your basket is empty</Text><TouchableOpacity onPress={()=>setScreen('products')}><Text style={s.link}>Browse products</Text></TouchableOpacity></View>:<><Text style={s.note}>{lines.length} different products</Text>{lines.map(p=><View key={p.id} style={s.line}><Image source={{uri:p.image}} style={s.thumb}/><View style={{flex:1}}><Text style={s.brand}>{p.brand}</Text><Text style={s.lineName}>{p.name}</Text><Text style={s.pack}>{p.pack}</Text></View><View style={s.qty}><TouchableOpacity onPress={()=>remove(p)}><Text style={s.qtyBtn}>−</Text></TouchableOpacity><Text style={s.qtyNum}>{p.qty}</Text><TouchableOpacity onPress={()=>add(p)}><Text style={s.qtyBtn}>+</Text></TouchableOpacity></View></View>)}<TouchableOpacity style={s.compare} onPress={()=>setScreen('compare')}><Text style={s.compareText}>Compare full basket</Text></TouchableOpacity></>}</>}
 {screen==='compare'&&<><Text style={s.note}>Test prices only · loyalty price shown where available</Text>{totals.map((x,i)=><View key={x.id} style={[s.shop,i===0&&s.winner]}>{i===0&&<Text style={s.cheapest}>CHEAPEST</Text>}<Text style={s.shopName}>{x.name}</Text><View style={s.shopRow}><View><Text style={s.small}>Normal price</Text><Text style={s.normal}>{money(x.normal)}</Text></View><View style={{alignItems:'flex-end'}}><Text style={s.small}>Your loyalty price</Text><Text style={s.total}>{money(x.loyalty)}</Text></View></View><Text style={s.found}>✓ {lines.length}/{lines.length} products matched</Text><TouchableOpacity style={[s.choose,i!==0&&s.chooseAlt]}><Text style={[s.chooseText,i!==0&&{color:C.green}]}>Choose {x.name}</Text></TouchableOpacity></View>)}</>}
 </ScrollView><View style={s.nav}><TouchableOpacity onPress={()=>setScreen('products')}><Text style={[s.navText,screen==='products'&&s.active]}>Products</Text></TouchableOpacity><TouchableOpacity onPress={()=>setScreen('basket')}><Text style={[s.navText,screen==='basket'&&s.active]}>Basket</Text></TouchableOpacity><TouchableOpacity disabled={!lines.length} onPress={()=>setScreen('compare')}><Text style={[s.navText,screen==='compare'&&s.active]}>Compare</Text></TouchableOpacity></View></SafeAreaView>
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.cream},top:{padding:20,paddingTop:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:C.green},logo:{fontSize:27,fontWeight:'900',color:C.ink,marginTop:3},basketBtn:{backgroundColor:C.green,borderRadius:16,padding:12},basketText:{color:C.white,fontWeight:'900'},page:{padding:18,paddingBottom:90},search:{height:50,backgroundColor:C.white,borderRadius:16,paddingHorizontal:16,fontSize:15},note:{fontSize:12,color:C.muted,marginVertical:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},product:{width:'48%',backgroundColor:C.white,borderRadius:18,padding:10},image:{width:'100%',aspectRatio:1,borderRadius:13,backgroundColor:C.soft},brand:{fontSize:10,fontWeight:'900',color:C.green,textTransform:'uppercase',marginTop:8},productName:{fontSize:14,fontWeight:'800',color:C.ink,minHeight:36,marginTop:2},pack:{fontSize:11,color:C.muted,marginTop:2},priceRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:10},from:{fontSize:12,fontWeight:'800'},add:{backgroundColor:C.green,borderRadius:10,paddingVertical:7,paddingHorizontal:10},addText:{color:C.white,fontWeight:'900',fontSize:11},line:{backgroundColor:C.white,borderRadius:17,padding:11,marginBottom:9,flexDirection:'row',alignItems:'center',gap:11},thumb:{width:60,height:60,borderRadius:12},lineName:{fontWeight:'800',fontSize:14,color:C.ink},qty:{flexDirection:'row',alignItems:'center',gap:10},qtyBtn:{fontSize:22,fontWeight:'700',color:C.green},qtyNum:{fontWeight:'900'},compare:{backgroundColor:C.green,borderRadius:17,padding:16,alignItems:'center',marginTop:10},compareText:{color:C.white,fontWeight:'900'},empty:{alignItems:'center',paddingTop:90},emptyIcon:{fontSize:45},emptyTitle:{fontSize:20,fontWeight:'900',marginTop:12},link:{color:C.green,fontWeight:'900',marginTop:10},shop:{backgroundColor:C.white,borderRadius:22,padding:18,marginBottom:13,borderWidth:1,borderColor:C.line},winner:{borderWidth:2,borderColor:C.green},cheapest:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:C.green},shopName:{fontSize:23,fontWeight:'900',marginTop:3,color:C.ink},shopRow:{flexDirection:'row',justifyContent:'space-between',marginTop:17},small:{fontSize:11,color:C.muted},normal:{fontSize:17,fontWeight:'700',marginTop:3},total:{fontSize:25,fontWeight:'900',color:C.green,marginTop:2},found:{fontSize:12,color:C.green,fontWeight:'700',marginTop:14},choose:{backgroundColor:C.green,borderRadius:14,padding:13,alignItems:'center',marginTop:13},chooseAlt:{backgroundColor:C.soft},chooseText:{color:C.white,fontWeight:'900'},nav:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:C.white,borderTopWidth:1,borderColor:C.line,padding:17,flexDirection:'row',justifyContent:'space-around'},navText:{fontWeight:'800',color:C.muted},active:{color:C.green}});
